import {StyleSheet} from 'react-native';
import {heightPercentageToDP as hp} from 'react-native-responsive-screen';
import {white, lineColor} from '../../themes/colors';

const styles = StyleSheet.create({
  topHeader: {
    height: 45,
    backgroundColor: white,
    width: '100%',
    position: 'absolute',
    borderColor: lineColor,
    borderBottomWidth: StyleSheet.hairlineWidth,
    zIndex: 1,
    top: 0,
  },
  bottomHeader: {
    height: 50,
    backgroundColor: white,
    width: '100%',
    position: 'absolute',
    borderColor: lineColor,
    borderTopWidth: StyleSheet.hairlineWidth,
    zIndex: 1,
    bottom: 0,
    transform: [{translateY: 50}],
  },
  bgImage: {
    flexGrow: 1,
    width: '100%',
    height: '100%',
  },
  sideHeader: {
    width: 45,
    height: 'auto',
    backgroundColor: white,
    position: 'absolute',
    borderColor: lineColor,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    zIndex: 1,
    transform: [{translateX: -45}],
    top: hp('100%') / 2.6,
    borderRadius: 5,
  },
  sideHeaderPoint: {
    width: 20,
    height: 50,
    backgroundColor: white,
    position: 'absolute',
    borderColor: lineColor,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    top: hp('100%') / 2.6,
    borderRadius: 2,
    justifyContent: 'center',
    transform: [{translateX: -20}],
    alignItems: 'center',
  },
  sidePointButton: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorPickerModal: {
    margin: 0,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  colorPickerView: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  colorPicker: {
    width: '90%',
    height: '60%',
  },
  doneContainer: {
    width: '100%',
    height: 45,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  doneButton: {
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  doneText: {
    color: '#333',
    fontWeight: '500',
    fontSize: 14,
  },
  usedColorsContainer: {
    width: '92%',
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    marginBottom: 10,
  },
  usedColorsText: {
    color: '#333',
    fontWeight: '500',
    fontSize: 22,
  },
  usedColors: {
    marginTop: 10,
    width: '100%',
    height: '100%',
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  usedColorBtn: {
    margin: 8,
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
